version: '3'

services:

#  spring:
#    container_name: spring
#    image: spring:test
#    restart: always
#    ports:
#      - 8082:8082
#    depends_on:
#      - mysql
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 500M
#        reservations:
#          cpus: '0.25'
#          memory: 250M

  mysql:
    container_name: mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - 9000:9000
      - 9092:9092

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
#    restart: always
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    #restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    #restart: always
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    depends_on:
      - prometheus

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}
# docker run -d -p 8081:8081 --name nexuswitoutvars sonatype/nexus3 => curl http://localhost:8081/nexus/service/local/status